import type {
  ConsultantSummary, Lead, LeadListItem, LeadSource, Program, PaymentMethod,
  RegressionReason, StageGuide, PipelineAction, KpiSummary, LeaderboardEntry,
  PersonalProfile, CoDeal, Enrollment, UserProfile
} from '../shared/types';

export const MOCK_CONSULTANTS: ConsultantSummary[] = [
  {
    id: 'c1',
    full_name: 'Linh Nguyễn',
    avatar_url: null,
    role: 'consultant',
    team_id: 't1',
    team_name: 'Team Alpha',
  },
  {
    id: 'c2',
    full_name: 'Minh Trần',
    avatar_url: null,
    role: 'leader',
    team_id: 't1',
    team_name: 'Team Alpha',
  },
  {
    id: 'c3',
    full_name: 'Hà Phạm',
    avatar_url: null,
    role: 'consultant',
    team_id: 't2',
    team_name: 'Team Beta',
  },
];

export const MOCK_CURRENT_USER: UserProfile = {
  id: 'c1',
  full_name: 'Linh Nguyễn',
  email: 'linh.nguyen@nedu.vn',
  avatar_url: null,
  role: 'consultant',
  team_id: 't1',
  team_name: 'Team Alpha',
  permissions: ['leads:read', 'leads:write', 'pipeline:advance', 'notes:write'],
};

export const MOCK_SOURCES: LeadSource[] = [
  { id: 's1', code: 'nedu_vn', label: 'nedu.vn', color_hex: '#6366F1' },
  { id: 's2', code: 'facebook_ads', label: 'Facebook Ads', color_hex: '#1877F2' },
  { id: 's3', code: 'referral', label: 'Giới thiệu', color_hex: '#10B981' },
  { id: 's4', code: 'zalo', label: 'Zalo', color_hex: '#0068FF' },
];

export const MOCK_PROGRAMS: Program[] = [
  { id: 'p1', code: 'la_chinh_minh', name: 'Là Chính Mình', base_price: 70000000, currency: 'VND' },
  { id: 'p2', code: 'adult_learning', name: 'Adult Learning', base_price: 45000000, currency: 'VND' },
  { id: 'p3', code: 'executive', name: 'Executive Program', base_price: 120000000, currency: 'VND' },
  { id: 'p4', code: 'short_course', name: 'Short Course', base_price: 15000000, currency: 'VND' },
  { id: 'p5', code: 'corporate', name: 'Corporate Training', base_price: 200000000, currency: 'VND' },
];

export const MOCK_PAYMENT_METHODS: PaymentMethod[] = [
  { id: 'pm1', code: 'bank_transfer', label: 'Chuyển khoản ngân hàng' },
  { id: 'pm2', code: 'credit_card', label: 'Thẻ tín dụng' },
  { id: 'pm3', code: 'e_wallet', label: 'Ví điện tử (MoMo/ZaloPay)' },
];

export const MOCK_REGRESSION_REASONS: RegressionReason[] = [
  { id: 'rr1', code: 'price_concern', label: 'Băn khoăn về học phí', is_custom: false },
  { id: 'rr2', code: 'need_more_time', label: 'Cần thêm thời gian suy nghĩ', is_custom: false },
  { id: 'rr3', code: 'family_issue', label: 'Vấn đề gia đình', is_custom: false },
  { id: 'rr4', code: 'work_schedule', label: 'Bận công việc', is_custom: false },
  { id: 'rr5', code: 'not_ready', label: 'Chưa sẵn sàng tâm lý', is_custom: false },
  { id: 'rr6', code: 'other', label: 'Lý do khác', is_custom: true },
];

export const MOCK_STAGE_GUIDES: StageGuide[] = [
  {
    stage: 'awareness',
    title: 'Tiếp Cận & Khai Thác',
    eyebrow_label: 'AWARENESS',
    color_hex: '#EF4444',
    action_label: 'Chuyển sang Interest →',
    script_template: 'Chào [Tên], mình là [Tên TV] từ Nedu. Mình thấy bạn quan tâm đến chủ đề phát triển bản thân. Bạn có thể chia sẻ hiện tại bạn đang gặp khó khăn gì không?',
    checklist_items: [
      { id: 'aw1', text: 'Xác nhận thông tin liên hệ (phone/email)', order: 1 },
      { id: 'aw2', text: 'Tìm hiểu nguồn tiếp cận của học viên', order: 2 },
      { id: 'aw3', text: 'Giới thiệu sơ lược về Nedu', order: 3 },
      { id: 'aw4', text: 'Tạo kết nối ban đầu (Zalo/Facebook)', order: 4 },
    ],
  },
  {
    stage: 'interest',
    title: 'Khơi Gợi Nhu Cầu',
    eyebrow_label: 'INTEREST',
    color_hex: '#F59E0B',
    action_label: 'Chuyển sang Consideration →',
    script_template: 'Bạn [Tên], để mình hiểu hơn về tình huống của bạn — điều gì khiến bạn cảm thấy mình cần thay đổi lúc này? Bạn kỳ vọng sau khóa học mình sẽ thay đổi được điều gì?',
    checklist_items: [
      { id: 'in1', text: 'Lắng nghe pain points của học viên', order: 1 },
      { id: 'in2', text: 'Xác định mục tiêu chính của học viên', order: 2 },
      { id: 'in3', text: 'Chia sẻ success story liên quan', order: 3 },
      { id: 'in4', text: 'Gửi tài liệu giới thiệu chương trình', order: 4 },
      { id: 'in5', text: 'Đặt lịch gặp/tư vấn chuyên sâu', order: 5 },
    ],
  },
  {
    stage: 'consideration',
    title: 'Tư Vấn Chuyên Sâu',
    eyebrow_label: 'CONSIDERATION',
    color_hex: '#EAB308',
    action_label: 'Chuyển sang Intent →',
    script_template: 'Qua buổi nói chuyện hôm nay, mình thấy chương trình [Tên CT] rất phù hợp với hoàn cảnh của bạn vì... Bạn cảm thấy thế nào về lộ trình này?',
    checklist_items: [
      { id: 'co1', text: 'Trình bày chi tiết chương trình phù hợp', order: 1 },
      { id: 'co2', text: 'Demo/chia sẻ nội dung học thử', order: 2 },
      { id: 'co3', text: 'Giải đáp thắc mắc về học phí và lộ trình', order: 3 },
      { id: 'co4', text: 'Kết nối với alumni để học viên tham khảo', order: 4 },
      { id: 'co5', text: 'Xử lý objections chính', order: 5 },
    ],
  },
  {
    stage: 'intent',
    title: 'Chốt Deal & Thanh Toán',
    eyebrow_label: 'INTENT',
    color_hex: '#22C55E',
    action_label: '✅ Xác nhận Enrolled',
    script_template: 'Tuyệt vời! Mình rất vui khi bạn đã sẵn sàng bắt đầu hành trình. Để hoàn tất đăng ký, mình sẽ gửi thông tin thanh toán cho bạn. Bạn dự kiến có thể chuyển khoản trong vòng 24h không?',
    checklist_items: [
      { id: 'it1', text: 'Xác nhận quyết định đăng ký của học viên', order: 1 },
      { id: 'it2', text: 'Gửi thông tin thanh toán chi tiết', order: 2 },
      { id: 'it3', text: 'Theo dõi tiến độ thanh toán', order: 3 },
      { id: 'it4', text: 'Xác nhận đã nhận đủ học phí', order: 4 },
    ],
  },
  {
    stage: 'enrolled',
    title: 'Onboarding Học Viên',
    eyebrow_label: 'ENROLLED',
    color_hex: '#3B82F6',
    action_label: 'Chuyển sang Retention →',
    script_template: 'Chúc mừng bạn [Tên] đã chính thức là thành viên của Nedu! Tài khoản học tập của bạn đã được kích hoạt. Lớp học bắt đầu vào [Ngày]. Bạn có câu hỏi gì không?',
    checklist_items: [
      { id: 'en1', text: 'Kích hoạt tài khoản học tập', order: 1 },
      { id: 'en2', text: 'Gửi email chào mừng và thông tin lớp học', order: 2 },
      { id: 'en3', text: 'Thêm học viên vào nhóm Zalo/Facebook', order: 3 },
      { id: 'en4', text: 'Giới thiệu với giảng viên phụ trách', order: 4 },
    ],
  },
  {
    stage: 'retention',
    title: 'Chăm Sóc & Tái Ký',
    eyebrow_label: 'RETENTION',
    color_hex: '#8B5CF6',
    action_label: 'Hoàn thành chăm sóc ✓',
    script_template: 'Chào [Tên], mình muốn hỏi thăm tiến độ học của bạn. Bạn đang học đến đâu rồi? Có điều gì cần hỗ trợ thêm không? Nedu vừa ra chương trình nâng cao mà mình nghĩ rất phù hợp với bạn...',
    checklist_items: [
      { id: 're1', text: 'Check-in tiến độ học tập hàng tuần', order: 1 },
      { id: 're2', text: 'Thu thập feedback về khóa học', order: 2 },
      { id: 're3', text: 'Giới thiệu chương trình nâng cao', order: 3 },
      { id: 're4', text: 'Mời tham gia chương trình referral', order: 4 },
    ],
  },
];

export const MOCK_CO_DEAL: CoDeal = {
  id: 'cd1',
  lead_id: 'l3',
  primary_consultant: MOCK_CONSULTANTS[0],
  co_consultant: MOCK_CONSULTANTS[1],
  primary_share_pct: 70,
  co_share_pct: 30,
  note: 'Lead được Minh hỗ trợ buổi tư vấn chuyên sâu về chương trình Executive',
  status: 'active',
  created_at: '2026-04-10T09:00:00Z',
};

export const MOCK_ENROLLMENT: Enrollment = {
  id: 'enr1',
  lead_id: 'l5',
  program: MOCK_PROGRAMS[0],
  primary_consultant: MOCK_CONSULTANTS[0],
  co_deal: null,
  amount_paid: 70000000,
  currency: 'VND',
  payment_method: MOCK_PAYMENT_METHODS[0],
  transaction_ref: 'TXN20260412001',
  student_account_status: 'activated',
  activation_email_sent_at: '2026-04-12T10:30:00Z',
  learn_account_id: 'student_12345',
  enrolled_at: '2026-04-12T10:00:00Z',
};

export const MOCK_LEADS: Lead[] = [
  {
    id: 'l1',
    person: {
      id: 'p1',
      full_name: 'Nguyễn Thị Thu Hương',
      phone: '0901234567',
      email: 'huong.nguyen@gmail.com',
      date_of_birth: '1990-05-15',
      time_of_birth: '08:30',
      occupation: 'Kế toán trưởng',
      avatar_url: null,
      goals: 'Muốn tìm lại bản thân, vượt qua giai đoạn burnout',
      pain_points: 'Cảm thấy mất phương hướng, áp lực công việc quá lớn',
    },
    parent_lead_id: null,
    source: MOCK_SOURCES[1],
    assigned_consultant: MOCK_CONSULTANTS[0],
    current_stage: 'awareness',
    status: 'active',
    sla_status: { status: 'breached', hours_elapsed: 26, badge_text: 'Quá hạn 26h' },
    quiz_score: null,
    profile_completion_pct: 45,
    is_returning: false,
    first_contact_at: '2026-04-10T08:00:00Z',
    last_contact_at: '2026-04-11T14:00:00Z',
    enrolled_at: null,
    co_deal: null,
    enrollment: null,
    created_at: '2026-04-10T08:00:00Z',
    updated_at: '2026-04-11T14:00:00Z',
  },
  {
    id: 'l2',
    person: {
      id: 'p2',
      full_name: 'Trần Văn Đức',
      phone: '0912345678',
      email: 'duc.tran@outlook.com',
      date_of_birth: '1985-11-22',
      time_of_birth: '14:00',
      occupation: 'Giám đốc kinh doanh',
      avatar_url: null,
      goals: 'Nâng cao năng lực lãnh đạo và quản lý đội nhóm',
      pain_points: 'Đội nhóm thiếu đoàn kết, hiệu suất làm việc thấp',
    },
    parent_lead_id: null,
    source: MOCK_SOURCES[2],
    assigned_consultant: MOCK_CONSULTANTS[0],
    current_stage: 'interest',
    status: 'active',
    sla_status: { status: 'warning', hours_elapsed: 20, badge_text: 'Sắp quá hạn' },
    quiz_score: 78,
    profile_completion_pct: 70,
    is_returning: false,
    first_contact_at: '2026-04-09T10:00:00Z',
    last_contact_at: '2026-04-12T09:00:00Z',
    enrolled_at: null,
    co_deal: null,
    enrollment: null,
    created_at: '2026-04-09T10:00:00Z',
    updated_at: '2026-04-12T09:00:00Z',
  },
  {
    id: 'l3',
    person: {
      id: 'p3',
      full_name: 'Lê Thị Mai Anh',
      phone: '0923456789',
      email: 'maianh.le@company.vn',
      date_of_birth: '1988-03-08',
      time_of_birth: '06:00',
      occupation: 'HR Manager',
      avatar_url: null,
      goals: 'Phát triển kỹ năng coaching và mentoring',
      pain_points: 'Khó truyền cảm hứng cho nhân viên trẻ',
    },
    parent_lead_id: null,
    source: MOCK_SOURCES[0],
    assigned_consultant: MOCK_CONSULTANTS[0],
    current_stage: 'consideration',
    status: 'active',
    sla_status: { status: 'ok', hours_elapsed: 5, badge_text: null },
    quiz_score: 85,
    profile_completion_pct: 88,
    is_returning: false,
    first_contact_at: '2026-04-08T09:00:00Z',
    last_contact_at: '2026-04-13T08:00:00Z',
    enrolled_at: null,
    co_deal: MOCK_CO_DEAL,
    enrollment: null,
    created_at: '2026-04-08T09:00:00Z',
    updated_at: '2026-04-13T08:00:00Z',
  },
  {
    id: 'l4',
    person: {
      id: 'p4',
      full_name: 'Phạm Quốc Hùng',
      phone: '0934567890',
      email: 'hung.pham@gmail.com',
      date_of_birth: '1982-07-30',
      time_of_birth: '20:00',
      occupation: 'CEO Startup',
      avatar_url: null,
      goals: 'Tìm kiếm sự bình an nội tâm và cân bằng cuộc sống',
      pain_points: 'Bị cuốn vào vòng xoáy công việc, thiếu thời gian cho gia đình',
    },
    parent_lead_id: null,
    source: MOCK_SOURCES[3],
    assigned_consultant: MOCK_CONSULTANTS[0],
    current_stage: 'intent',
    status: 'active',
    sla_status: { status: 'ok', hours_elapsed: 2, badge_text: null },
    quiz_score: 92,
    profile_completion_pct: 95,
    is_returning: true,
    first_contact_at: '2026-04-07T08:00:00Z',
    last_contact_at: '2026-04-13T07:00:00Z',
    enrolled_at: null,
    co_deal: null,
    enrollment: null,
    created_at: '2026-04-07T08:00:00Z',
    updated_at: '2026-04-13T07:00:00Z',
  },
  {
    id: 'l5',
    person: {
      id: 'p5',
      full_name: 'Hoàng Thị Lan',
      phone: '0945678901',
      email: 'lan.hoang@edu.vn',
      date_of_birth: '1993-12-01',
      time_of_birth: '11:30',
      occupation: 'Giáo viên THPT',
      avatar_url: null,
      goals: 'Nâng cao năng lực giảng dạy và kết nối học sinh',
      pain_points: 'Thiếu công cụ và phương pháp tiếp cận học sinh thế hệ Z',
    },
    parent_lead_id: null,
    source: MOCK_SOURCES[0],
    assigned_consultant: MOCK_CONSULTANTS[0],
    current_stage: 'enrolled',
    status: 'closed_won',
    sla_status: { status: 'ok', hours_elapsed: 0, badge_text: null },
    quiz_score: 88,
    profile_completion_pct: 100,
    is_returning: false,
    first_contact_at: '2026-04-01T09:00:00Z',
    last_contact_at: '2026-04-12T10:00:00Z',
    enrolled_at: '2026-04-12T10:00:00Z',
    co_deal: null,
    enrollment: MOCK_ENROLLMENT,
    created_at: '2026-04-01T09:00:00Z',
    updated_at: '2026-04-12T10:00:00Z',
  },
  {
    id: 'l6',
    person: {
      id: 'p6',
      full_name: 'Võ Minh Khoa',
      phone: '0956789012',
      email: 'khoa.vo@business.vn',
      date_of_birth: '1987-09-14',
      time_of_birth: '16:45',
      occupation: 'Trưởng phòng Marketing',
      avatar_url: null,
      goals: 'Xây dựng thương hiệu cá nhân và mạng lưới kết nối',
      pain_points: 'Thiếu tự tin khi giao tiếp và thuyết trình trước đám đông',
    },
    parent_lead_id: null,
    source: MOCK_SOURCES[1],
    assigned_consultant: MOCK_CONSULTANTS[0],
    current_stage: 'awareness',
    status: 'active',
    sla_status: { status: 'breached', hours_elapsed: 48, badge_text: 'Quá hạn 48h' },
    quiz_score: null,
    profile_completion_pct: 30,
    is_returning: false,
    first_contact_at: '2026-04-11T13:00:00Z',
    last_contact_at: '2026-04-11T13:00:00Z',
    enrolled_at: null,
    co_deal: null,
    enrollment: null,
    created_at: '2026-04-11T13:00:00Z',
    updated_at: '2026-04-11T13:00:00Z',
  },
  {
    id: 'l7',
    person: {
      id: 'p7',
      full_name: 'Nguyễn Thị Bảo Châu',
      phone: '0967890123',
      email: 'chau.nguyen@gmail.com',
      date_of_birth: '1995-02-28',
      time_of_birth: '09:15',
      occupation: 'Freelancer / Content Creator',
      avatar_url: null,
      goals: 'Định hướng nghề nghiệp và phát triển bền vững',
      pain_points: 'Thu nhập không ổn định, không biết mình muốn gì',
    },
    parent_lead_id: null,
    source: MOCK_SOURCES[3],
    assigned_consultant: MOCK_CONSULTANTS[0],
    current_stage: 'interest',
    status: 'active',
    sla_status: { status: 'ok', hours_elapsed: 8, badge_text: null },
    quiz_score: 65,
    profile_completion_pct: 60,
    is_returning: true,
    first_contact_at: '2026-04-12T10:00:00Z',
    last_contact_at: '2026-04-13T06:00:00Z',
    enrolled_at: null,
    co_deal: null,
    enrollment: null,
    created_at: '2026-04-12T10:00:00Z',
    updated_at: '2026-04-13T06:00:00Z',
  },
  {
    id: 'l8',
    person: {
      id: 'p8',
      full_name: 'Đỗ Thanh Tùng',
      phone: '0978901234',
      email: 'tung.do@corp.vn',
      date_of_birth: '1980-06-20',
      time_of_birth: '07:00',
      occupation: 'Phó Tổng Giám Đốc',
      avatar_url: null,
      goals: 'Lãnh đạo xuất sắc trong giai đoạn chuyển đổi số',
      pain_points: 'Khó thích nghi với thay đổi nhanh, đội nhóm kháng cự',
    },
    parent_lead_id: null,
    source: MOCK_SOURCES[2],
    assigned_consultant: MOCK_CONSULTANTS[0],
    current_stage: 'consideration',
    status: 'active',
    sla_status: { status: 'warning', hours_elapsed: 18, badge_text: 'Sắp quá hạn' },
    quiz_score: 90,
    profile_completion_pct: 80,
    is_returning: false,
    first_contact_at: '2026-04-05T08:00:00Z',
    last_contact_at: '2026-04-12T16:00:00Z',
    enrolled_at: null,
    co_deal: null,
    enrollment: null,
    created_at: '2026-04-05T08:00:00Z',
    updated_at: '2026-04-12T16:00:00Z',
  },
];

export const MOCK_LEAD_LIST_ITEMS: LeadListItem[] = MOCK_LEADS.map(lead => ({
  id: lead.id,
  full_name: lead.person.full_name,
  phone: lead.person.phone,
  avatar_url: lead.person.avatar_url,
  current_stage: lead.current_stage,
  status: lead.status,
  sla_status: lead.sla_status,
  action_label: getActionLabel(lead.current_stage),
  priority: getPriority(lead.sla_status.status, lead.current_stage),
  source_code: lead.source.code,
  source_label: lead.source.label,
  is_returning: lead.is_returning,
  has_co_deal: !!lead.co_deal,
  profile_hint: getProfileHint(lead),
  assigned_consultant_id: lead.assigned_consultant?.id ?? null,
  created_at: lead.created_at,
}));

function getActionLabel(stage: string): string {
  switch (stage) {
    case 'awareness': return 'GỌI NGAY';
    case 'interest': return 'TƯ VẤN';
    case 'consideration': return 'TƯ VẤN SÂU';
    case 'intent': return 'CHỐT DEAL';
    case 'enrolled': return 'ONBOARD';
    case 'retention': return 'CHĂM SÓC';
    default: return 'XEM';
  }
}

function getPriority(slaStatus: string, stage: string): 'urgent' | 'today' | 'week' | 'done' {
  if (slaStatus === 'breached') return 'urgent';
  if (slaStatus === 'warning') return 'today';
  if (stage === 'enrolled') return 'done';
  return 'week';
}

function getProfileHint(lead: Lead): string | null {
  if (lead.person.goals) return lead.person.goals.substring(0, 60) + '...';
  return null;
}

export const MOCK_TIMELINE_ITEMS: PipelineAction[] = [
  {
    id: 'pa1',
    lead_id: 'l3',
    actor: MOCK_CONSULTANTS[0],
    action_type: 'note_added',
    action_icon: '📝',
    action_label: 'Đã thêm ghi chú',
    from_stage: null,
    to_stage: null,
    regression_reason: null,
    note_content: 'Học viên rất hứng thú với chương trình Là Chính Mình. Cần follow-up về học phí và lộ trình thanh toán.',
    payload: {},
    created_at: '2026-04-13T08:30:00Z',
  },
  {
    id: 'pa2',
    lead_id: 'l3',
    actor: MOCK_CONSULTANTS[1],
    action_type: 'co_deal_created',
    action_icon: '🤝',
    action_label: 'Tạo Co-Deal',
    from_stage: null,
    to_stage: null,
    regression_reason: null,
    note_content: 'Hỗ trợ tư vấn chuyên sâu về chương trình Executive',
    payload: { primary_share: 70, co_share: 30 },
    created_at: '2026-04-10T09:00:00Z',
  },
  {
    id: 'pa3',
    lead_id: 'l3',
    actor: MOCK_CONSULTANTS[0],
    action_type: 'stage_advanced',
    action_icon: '⬆️',
    action_label: 'Tiến stage',
    from_stage: 'interest',
    to_stage: 'consideration',
    regression_reason: null,
    note_content: null,
    payload: {},
    created_at: '2026-04-09T15:00:00Z',
  },
  {
    id: 'pa4',
    lead_id: 'l3',
    actor: MOCK_CONSULTANTS[0],
    action_type: 'note_added',
    action_icon: '📝',
    action_label: 'Đã thêm ghi chú',
    from_stage: null,
    to_stage: null,
    regression_reason: null,
    note_content: 'Đã gọi điện, học viên quan tâm đến lộ trình phát triển tư duy lãnh đạo.',
    payload: {},
    created_at: '2026-04-09T10:00:00Z',
  },
  {
    id: 'pa5',
    lead_id: 'l3',
    actor: MOCK_CONSULTANTS[0],
    action_type: 'stage_advanced',
    action_icon: '⬆️',
    action_label: 'Tiến stage',
    from_stage: 'awareness',
    to_stage: 'interest',
    regression_reason: null,
    note_content: null,
    payload: {},
    created_at: '2026-04-08T11:00:00Z',
  },
  {
    id: 'pa6',
    lead_id: 'l3',
    actor: null,
    action_type: 'assigned',
    action_icon: '👤',
    action_label: 'Phân công tư vấn viên',
    from_stage: null,
    to_stage: null,
    regression_reason: null,
    note_content: null,
    payload: { consultant_name: 'Linh Nguyễn' },
    created_at: '2026-04-08T09:00:00Z',
  },
];

export const MOCK_KPI_SUMMARY: KpiSummary = {
  period: '2026-04',
  total_leads_active: 7,
  enrolled_this_month: 3,
  leads_new_7d: 5,
  conversion_rate_pct: 42.8,
  revenue_this_month: 210000000,
  currency: 'VND',
  target_this_month: 500000000,
  target_progress_pct: 42,
  remaining_to_target: 290000000,
};

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  {
    rank: 1,
    consultant: MOCK_CONSULTANTS[1],
    enrolled: 5,
    target: 8,
    revenue: 350000000,
    progress_pct: 62.5,
    load_status: 'yellow',
    is_me: false,
    needs_support: false,
  },
  {
    rank: 2,
    consultant: MOCK_CONSULTANTS[0],
    enrolled: 3,
    target: 6,
    revenue: 210000000,
    progress_pct: 42,
    load_status: 'green',
    is_me: true,
    needs_support: false,
  },
  {
    rank: 3,
    consultant: MOCK_CONSULTANTS[2],
    enrolled: 1,
    target: 5,
    revenue: 70000000,
    progress_pct: 20,
    load_status: 'red',
    is_me: false,
    needs_support: true,
  },
];

export const MOCK_PERSONAL_PROFILE: PersonalProfile = {
  id: 'pp1',
  person_id: 'p3',
  hero_card: {
    quote: 'Người có tâm hồn nghệ sĩ ẩn sau vỏ bọc chuyên nghiệp — luôn tìm kiếm ý nghĩa sâu xa trong mọi việc',
    nhat_chu: 'Ất Mộc',
    life_path: 7,
    nine_star: 'Bạch Kim Tinh (6 Kim)',
  },
  core_personality_summary: 'Mai Anh là người có tư duy phân tích sắc bén kết hợp với trực giác nhạy cảm. Cô ấy thường tự đặt ra tiêu chuẩn cao cho bản thân và người khác, đôi khi khiến bản thân kiệt sức vì kỳ vọng quá lớn.',
  communication_dos: [
    'Trình bày logic, có số liệu và minh chứng cụ thể',
    'Tôn trọng sự riêng tư và không gian cá nhân',
    'Chia sẻ các câu chuyện thành công có chiều sâu',
    'Đặt câu hỏi mở để cô ấy tự khám phá',
  ],
  communication_donts: [
    'Không thúc ép hay tạo áp lực quyết định nhanh',
    'Tránh quá nhiều thông tin một lúc',
    'Không dùng cách tiếp cận quá hào hứng hoặc ồn ào',
    'Không so sánh với người khác',
  ],
  true_needs: 'Sự công nhận thực sự về năng lực, không gian để phát triển theo cách riêng, và cộng đồng đồng điệu về giá trị.',
  current_year_timing: '2026 là năm chuyển đổi quan trọng — sao 7 Đoài Kim vào cung trung tâm, thích hợp cho việc học hỏi kỹ năng mới và mở rộng mạng lưới quan hệ chuyên nghiệp.',
  opening_suggestion: 'Bắt đầu bằng: "Với tầm nhìn và sự nhạy cảm của bạn trong HR, tôi nghĩ chương trình này không chỉ giúp bạn coaching tốt hơn, mà còn chạm đến điều bạn thực sự đang tìm kiếm trong hành trình phát triển bản thân..."',
  generated_by: 'ai-engine-v2',
  generated_at: '2026-04-13T07:00:00Z',
};
